# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Mod Properties
mod_version=1.0.0
maven_group=fr.hugman
archives_base_name=ultimate_lucky_block

# Fabric Properties
# check these on https://fabricmc.net/develop/
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.152.2+26.2

# check this on https://nucleoid.xyz/use/
plasmid_version=0.7.2-SNAPSHOT+26.2

# check this on https://maven.nucleoid.xyz/#/releases/eu/pb4/polymer
polymer_version=0.17.3+26.2

# check this on https://maven.nucleoid.xyz/
uhc_version=4.0.0+d495208

# check this on https://maven.nucleoid.xyz/#/releases/xyz/nucleoid/server-translations-api
server_translations_api_version=3.1.0+26.2